server:
  port: 8085

spring:
  application:
    name: session-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/skillsync_session
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs

  servers:
    - url: http://api-gateway:8080/sessions
      description: Via API Gateway
    - url: http://session-service:8085
      description: Direct
